### PR TITLE
Adding the Queue Time parameter

### PR DESCRIPTION
**Pull request by axelay**
Added the Queue Time (qt) parameter to allow latent processing of events

### CODE REVIEW

**Comment by ins0** [comment]
Hey @axelay thanks for your pr. Unfortunately i have some questions with this implementation.

The ``qt`` param can be set to ensure that offline collected events (clicks, event...) are reported with the time they are collected and not when the call being received on the measurement api.

Therefore i think this option should be not set as an option as more events could be send with a different ``qt``. So allowing this option defined over the options feels wrong.

Did i get this right?

**Comment by axelay** [comment]
The qt parameters allow you to set a time difference in milliseconds between the time the event took place and the time it is sent as you rightly point out.
My scenario is that I queue up events in Redis to be sent with a cron job in the background so that I do not put more pressure on the core engine of the website. That works well but as you can imagine, the timestamps are messed up. 
When looping through all my events, I just need to call *$tracking->set_option('queue_time', now() - $event->timestamp);* before calling $tracing->sendTracking($event)

I do understand setting this as a **global** option feels wrong however there is no way to set this per event.

Hope that helps

**Comment by ins0** [comment]
Ok would it be possible that you create a new pr that adds the ``qt`` param to the https://github.com/ins0/google-measurement-php-client/blob/33fc1f72ae5b7a5ac1677ad4feb68462762dac2d/src/Racecore/GATracking/Tracking/AbstractTracking.php file.

So you then can set this options for every Tracking type. e.g. ``->setQueueTime($timeDiff)`` ?

**Comment by ins0** [comment]
@axelay Just for my own santiy, The ``qt`` param is in miliseconds but your example setting the param is in seconds :) idk if this is production code 

If you don't have the time to create a new PR i would do this, got a few minutes right now.

**Comment by axelay** [comment]
The code I gave you is a purely theorical example but yes the time difference is in milliseconds.
I let you do the changes as you know this a little bit better than I do :)

**Comment by ins0** [comment]
:) ok i will give u a ping. thanks @axelay

**Pull request closed without merging**
