### PR TITLE
Improved createConnection robustness and Exception throwing

### PR DESCRIPTION
**Pull request by daN4cat**
socket_connect could return FALSE because no Internet connection is available.
The code change considers the case and throws an additional exception.
Exceptions now have an error message based on socket_last_error.

See http://www.binarytides.com/php-socket-programming-tutorial/ as reference.

Corrected a typo in the function name createConnection.

### CODE REVIEW

**Comment by daN4cat** [comment]
Travis-CI is not failing on phpunit, test are passing.

**Comment by ins0** [comment]
@daN4cat thank you very much! i will gratefully merge this, but could you please change the formatting errors so phpcs won't break the build?

**Comment by daN4cat** [comment]
@ins0 formatting errors sorted, let's wait for CI to run to the end and give a green light.

**Comment by daN4cat** [comment]
@ins0 I don't get the problem anymore, if you could enlight me that would help here.

**Comment by ins0** [comment]
Looks like line 31 got whitespace between the lines

**Comment by daN4cat** [comment]
Bingo!

**Comment by daN4cat** [comment]
@ins0 any chance to merge this PR?

**Comment by ins0** [comment]
🍻🍺 👊🏻👍

**Comment by ins0** [comment]
Thank you!

**Pull request merged**
